"""Final working migration

Revision ID: 1a3f80373b92
Revises: 6a53c4c38d5a
Create Date: 2025-08-04 12:35:50.451527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a3f80373b92'
down_revision: Union[str, None] = '6a53c4c38d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('account_assignments', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('account_assignments', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('account_assignments', 'account_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index(op.f('idx_16642_sqlite_autoindex_account_assignments_1'), table_name='account_assignments')
    op.create_unique_constraint('_user_account_uc', 'account_assignments', ['user_id', 'account_id'])
    op.create_foreign_key(None, 'account_assignments', 'platform_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.alter_column('platform_accounts', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('platform_accounts', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('platform_accounts', 'search_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_index(op.f('idx_16637_sqlite_autoindex_platform_accounts_1'), table_name='platform_accounts')
    op.drop_index(op.f('idx_16637_sqlite_autoindex_platform_accounts_2'), table_name='platform_accounts')
    op.create_unique_constraint(None, 'platform_accounts', ['display_name'])
    op.create_unique_constraint(None, 'platform_accounts', ['search_name'])
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('products', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('products', 'photo_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('products', 'purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('products', 'platform_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.alter_column('sales', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sales', 'stock_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('sales', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('sales', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sales', 'account',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.alter_column('sales', 'label_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sales', 'screenshot_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sales', 'sale_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('sales', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('stock', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('stock', 'product_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('stock', 'size',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
    op.alter_column('stock', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_state', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('system_state', 'value',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('user_product_access', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_product_access', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user_product_access', 'product_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index(op.f('idx_16634_sqlite_autoindex_user_product_access_1'), table_name='user_product_access')
    op.create_unique_constraint('_user_product_uc', 'user_product_access', ['user_id', 'product_id'])
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('_user_product_uc', 'user_product_access', type_='unique')
    op.create_index(op.f('idx_16634_sqlite_autoindex_user_product_access_1'), 'user_product_access', ['user_id', 'product_id'], unique=True)
    op.alter_column('user_product_access', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('user_product_access', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('user_product_access', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('system_state', 'value',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('system_state', 'key',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('stock', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock', 'size',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('stock', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('stock', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sales', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('sales', 'sale_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('sales', 'screenshot_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sales', 'label_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sales', 'account',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sales', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sales', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('sales', 'stock_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('sales', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'platform_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('products', 'photo_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('products', 'category_id')
    op.drop_constraint(None, 'platform_accounts', type_='unique')
    op.drop_constraint(None, 'platform_accounts', type_='unique')
    op.create_index(op.f('idx_16637_sqlite_autoindex_platform_accounts_2'), 'platform_accounts', ['search_name'], unique=True)
    op.create_index(op.f('idx_16637_sqlite_autoindex_platform_accounts_1'), 'platform_accounts', ['display_name'], unique=True)
    op.alter_column('platform_accounts', 'search_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('platform_accounts', 'display_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('platform_accounts', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'account_assignments', type_='foreignkey')
    op.drop_constraint('_user_account_uc', 'account_assignments', type_='unique')
    op.create_index(op.f('idx_16642_sqlite_autoindex_account_assignments_1'), 'account_assignments', ['user_id', 'account_id'], unique=True)
    op.alter_column('account_assignments', 'account_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('account_assignments', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('account_assignments', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('categories')
    # ### end Alembic commands ###
