"""Add purchase_price to Product table

Revision ID: 5e44ece71617
Revises: 6fe51cfa1c6c
Create Date: 2025-07-20 14:28:54.292559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e44ece71617'
down_revision: Union[str, None] = '6fe51cfa1c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('purchase_price', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'purchase_price')
    # ### end Alembic commands ###
