"""Remove email from PlatformAccount

Revision ID: 604458551cc6
Revises: 85ffa6a8df90
Create Date: 2025-07-21 12:50:00.813232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604458551cc6'
down_revision: Union[str, None] = '85ffa6a8df90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.drop_column('email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=False, server_default='default@email.com'))
    # ### end Alembic commands ###
