"""Add is_confirmed to Sale with server_default

Revision ID: 6fe51cfa1c6c
Revises: eb7df6900141
Create Date: 2025-07-17 08:59:24.227666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe51cfa1c6c'
down_revision: Union[str, None] = 'eb7df6900141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('is_confirmed', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'is_confirmed')
    # ### end Alembic commands ###
