"""Add account field to Sale model

Revision ID: 9bc15d6fa7ae
Revises: 5e44ece71617
Create Date: 2025-07-20 14:58:35.780528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc15d6fa7ae'
down_revision: Union[str, None] = '5e44ece71617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('account', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'account')
    # ### end Alembic commands ###
