"""Add system_state table for counters

Revision ID: bbe2bcccbde0
Revises: b466f3ead8c3
Create Date: 2025-07-26 18:01:44.918849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe2bcccbde0'
down_revision: Union[str, None] = 'b466f3ead8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_state')
    # ### end Alembic commands ###
